name = "PhysicsEngine"
uuid = "547c94b8-caa0-11e8-3dc1-4fbbc3a0b290"
authors = ["jonathanbuchanan <jonathan.russ.buchanan@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
